- name: install webupd8 oracle java PPA
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present

- name: add key for webupd8 oracle java PPA
  apt_key: keyserver=keyserver.ubuntu.com id=EEA14886

- name: automatically select the Oracle License
  tags: java
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  changed_when: false

- name: install oracle JDK 7 and update apt cache
  apt: pkg=oracle-java7-installer state=latest update-cache=yes force=yes

- name: install necessary packages
  apt: pkg={{ item }} state=latest
  with_items:
    - vim
    - git
    - tar
    - tmux

- name: create dir to store BuildTools and all the stuff it downloads/compiles
  file: dest={{ src_dir }} mode=755 state=directory

- name: download BuildTools
  get_url: url=https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    dest={{ src_dir }}/BuildTools.jar

- name: run BuildTools to compile Spigot (will take a while)
  command: java -jar BuildTools.jar chdir={{ src_dir }}/

- name: create dir to store production server
  file: dest={{ prod_dir }} mode=755 state=directory

- name: get spigot jar file path
  shell: ls {{ src_dir }}/Spigot/Spigot-Server/target/spigot-*-SNAPSHOT.jar
  register: spigot_jar

- name: move compiled server jar to production dir
  command: cp {{ spigot_jar.stdout }} {{ prod_dir }}/spigot.jar

- name: create eula.txt
  template: src=eula.txt dest={{ prod_dir }}/eula.txt

- name: create server.properties
  template: src=server.properties dest={{ prod_dir }}/server.properties

- name: create startup script
  template: src=start.sh dest={{ prod_dir }}/start.sh mode=0744

- name: create tmux script
  template: src=tmux.sh dest={{ prod_dir }}/tmux.sh mode=0744

- name: kick off server in a tmux session
  command: ./tmux.sh chdir={{ prod_dir }}
